apiVersion: v1
kind: Service
metadata:
  name: grpc-gateway-service
spec:
  type: NodePort
  selector:
    app: grpc-gateway
  ports:
    - protocol: TCP
      nodePort: 30000
      port: 9000
      targetPort: 9000
